---
development:
  cloud_name: dn40jh1kc
  api_key: '935222421769436'
  api_secret: wYDSion3bQZKhiHY84lkL51xZn0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dn40jh1kc
  api_key: '935222421769436'
  api_secret: wYDSion3bQZKhiHY84lkL51xZn0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dn40jh1kc
  api_key: '935222421769436'
  api_secret: wYDSion3bQZKhiHY84lkL51xZn0
  enhance_image_tag: true
  static_image_support: false
